[package]
name = "rust_eveonline_esi"
version = "1.17.0"
authors = ["OpenAPI Generator team and contributors"]
description = "An OpenAPI for EVE Online"
# Override this license by providing a License Object in the OpenAPI.
license = "Unlicense"
edition = "2018"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
url = "^2.2"
uuid = { version = "^1.0", features = ["serde"] }
[dependencies.reqwest]
version = "^0.11"
features = ["json", "multipart"]
