/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.8.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetContractsPublicItemsContractIdForbidden : Forbidden



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractsPublicItemsContractIdForbidden {
    /// Forbidden message
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl GetContractsPublicItemsContractIdForbidden {
    /// Forbidden
    pub fn new() -> GetContractsPublicItemsContractIdForbidden {
        GetContractsPublicItemsContractIdForbidden {
            error: None,
        }
    }
}


