/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.8.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetCorporationsCorporationIdDivisionsOk : 200 ok object



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCorporationsCorporationIdDivisionsOk {
    /// hangar array
    #[serde(rename = "hangar", skip_serializing_if = "Option::is_none")]
    pub hangar: Option<Vec<crate::models::GetCorporationsCorporationIdDivisionsHangarHangar>>,
    /// wallet array
    #[serde(rename = "wallet", skip_serializing_if = "Option::is_none")]
    pub wallet: Option<Vec<crate::models::GetCorporationsCorporationIdDivisionsWalletWallet>>,
}

impl GetCorporationsCorporationIdDivisionsOk {
    /// 200 ok object
    pub fn new() -> GetCorporationsCorporationIdDivisionsOk {
        GetCorporationsCorporationIdDivisionsOk {
            hangar: None,
            wallet: None,
        }
    }
}


