/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.8.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetCharactersCharacterIdMedalsGraphic : graphic object



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCharactersCharacterIdMedalsGraphic {
    /// color integer
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<i32>,
    /// graphic string
    #[serde(rename = "graphic")]
    pub graphic: String,
    /// layer integer
    #[serde(rename = "layer")]
    pub layer: i32,
    /// part integer
    #[serde(rename = "part")]
    pub part: i32,
}

impl GetCharactersCharacterIdMedalsGraphic {
    /// graphic object
    pub fn new(graphic: String, layer: i32, part: i32) -> GetCharactersCharacterIdMedalsGraphic {
        GetCharactersCharacterIdMedalsGraphic {
            color: None,
            graphic,
            layer,
            part,
        }
    }
}


