/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.8.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetUniverseStargatesStargateIdDestination : destination object



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUniverseStargatesStargateIdDestination {
    /// The stargate this stargate connects to
    #[serde(rename = "stargate_id")]
    pub stargate_id: i32,
    /// The solar system this stargate connects to
    #[serde(rename = "system_id")]
    pub system_id: i32,
}

impl GetUniverseStargatesStargateIdDestination {
    /// destination object
    pub fn new(stargate_id: i32, system_id: i32) -> GetUniverseStargatesStargateIdDestination {
        GetUniverseStargatesStargateIdDestination {
            stargate_id,
            system_id,
        }
    }
}


