/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.8.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Unauthorized : Unauthorized model



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Unauthorized {
    /// Unauthorized message
    #[serde(rename = "error")]
    pub error: String,
}

impl Unauthorized {
    /// Unauthorized model
    pub fn new(error: String) -> Unauthorized {
        Unauthorized {
            error,
        }
    }
}


